---
title: "Creating Subsets for MDCC Training"
author: "Emily Chen"
date: "2023-11-13"
output: html_document
---

# 1 Setup

## 1.1 Load packages

```{r}
library(ggfortify)
library(ggplot2)
library(dplyr)
```

Creates subset of files in "upload_chorus_frog_data" directory for each site based on if they are classified or not. Also renames files with absent_x and present_x.
```{r}
Pfer_clean <- read.csv("../data/csv_files/Pfer_clean.csv")

# Specify the root directory
root_directory <- "~/Library/CloudStorage/Box-Box/innovations-research-tech/PAM/DukeForestAcousticData"
new_directory <- file.path(root_directory, "upload_chorus_frog_data")

# Get a list of directories in the root directory
all_directories <- list.dirs(root_directory, recursive = FALSE)

# Loop through each directory
for (old_directory in all_directories) {
  # Extract the site name from the directory path
  site_name <- basename(old_directory)

  # Create the new directory for subsets
  if (!file.exists(new_directory)) {
    dir.create(new_directory)
  }

  # Get a list of files in the old directory
  all_files <- list.files(old_directory, pattern = ".wav", full.names = TRUE)

  # Filter files based on the conditions in Pfer_clean dataframe
  files_in_dataframe <- Pfer_clean$Filename[
    Pfer_clean$Validation %in% c("present", "absent") &
    Pfer_clean$Site == site_name
  ]

  # Create a subset of files based on the condition
  file_subset <- all_files[basename(all_files) %in% files_in_dataframe]

  # Rename and copy the subset of files to the new directory
  counter <- 1
  for (file_path in file_subset) {
    validation_label <- Pfer_clean$Validation[Pfer_clean$Filename == basename(file_path)]
    new_file_name <- paste(validation_label, counter, sep = "_")
    new_file_name <- paste(new_file_name, site_name, sep = "_")
    new_file_name <- paste0(new_file_name, ".wav")
    new_file_path <- file.path(new_directory, new_file_name)
    file.copy(file_path, new_file_path)
    cat("Copied file:", file_path, "to", new_file_path, "\n")
    counter <- counter + 1
  }
}
```

```{r}
MyFeatureDataFrame <- MFCCFunction(input.dir ="~/Library/CloudStorage/Box-Box/innovations-research-tech/PAM/DukeForestAcousticData/upload_chorus_frog_data", min.freq = 2500,max.freq = 3500)
```